apiVersion: v1
kind: Pod
metadata:
  name: multi-container-test-pod
  namespace: default
  annotations:
    workload-identity.io/inject-container-names: "app,sidecar"
spec:
  serviceAccountName: default
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: sidecar
    image: busybox:1.35
    command: ["sleep", "3600"]
  - name: logging
    image: fluent/fluent-bit:2.0
    command: ["sleep", "3600"]
  - name: monitoring
    image: prom/prometheus:v2.40.0
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: all-containers-test-pod
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: cache
    image: redis:7-alpine
  - name: db
    image: postgres:15-alpine
    env:
    - name: POSTGRES_DB
      value: testdb
    - name: POSTGRES_USER
      value: testuser
    - name: POSTGRES_PASSWORD
      value: testpass
---
apiVersion: v1
kind: Pod
metadata:
  name: init-containers-test-pod
  namespace: default
  annotations:
    workload-identity.io/inject-container-names: "init-secrets,app"
spec:
  serviceAccountName: default
  initContainers:
  - name: init-secrets
    image: vault:1.12
    command: ["vault", "kv", "get", "secret/app-config"]
  - name: init-local-setup
    image: busybox:1.35
    command: ["sh", "-c", "echo 'Local setup - no GCP access needed'"]
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: monitoring
    image: prom/prometheus:v2.40.0
    ports:
    - containerPort: 9090